seed: 42

# Data configuration
data:
  dataset_dir: './data'
  graph_pkl_filename: './data/adj_mx_bay.pkl'
  batch_size: 64 

# Model configuration
model:
  seq_length: 12  # 12 * 5min = 60 min history
  horizon: 12     # 12 * 5min = 60 min future prediction
  num_nodes: 325
  in_channels: 1  # Speed
  out_channels: 12 # Predicting 12 steps
  event_feature_dim: 7 # As defined in generate_event_features.py
  node_embedding_dim: 10
  d_k: 8 # Key/Query dimension for attention

# Training configuration
train:
  epochs: 100
  base_lr: 0.001
  weight_decay: 0.0001
  lr_patience: 5
  lr_decay_ratio: 0.1
  clip_grad_norm: 5.0
  log_dir: './logs'